"""Initial migration

Revision ID: 920e25e15534
Revises: 
Create Date: 2026-08-17 16:45:07.075182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920e25e15534'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'segment',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('NEW', 'REGULAR', 'LOYAL', 'VIP', name='customersegment'),
               nullable=False,
               existing_server_default=sa.text("'NEW'::character varying"))
    op.alter_column('customers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_customers_is_deleted'), 'customers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_customers_segment'), 'customers', ['segment'], unique=False)
    op.alter_column('inventory_adjustments', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'payment_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PAID', 'PENDING', 'PARTIAL', name='paymentstatus'),
               nullable=False,
               existing_server_default=sa.text("'PAID'::character varying"))
    op.alter_column('sales', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_sales_customer_id', table_name='sales')
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.alter_column('stock_movements', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.create_index('idx_sales_customer_id', 'sales', ['customer_id'], unique=False)
    op.alter_column('sales', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sales', 'payment_status',
               existing_type=sa.Enum('PAID', 'PENDING', 'PARTIAL', name='paymentstatus'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PAID'::character varying"))
    op.alter_column('inventory_adjustments', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_customers_segment'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_deleted'), table_name='customers')
    op.alter_column('customers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('customers', 'segment',
               existing_type=sa.Enum('NEW', 'REGULAR', 'LOYAL', 'VIP', name='customersegment'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'NEW'::character varying"))
    # ### end Alembic commands ###
