"""enhance_audit_logs_with_resource_fields

Revision ID: 9ab2c2293ff5
Revises: de2a3aaf1209
Create Date: 2026-09-15 13:16:53.605565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ab2c2293ff5'
down_revision: Union[str, None] = 'de2a3aaf1209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('resource_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('before_values', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('after_values', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('status', sa.String(), nullable=False, server_default='SUCCESS'))
    op.alter_column('audit_logs', 'entity_name', new_column_name='resource_type', existing_type=sa.String(), nullable=False)
    op.alter_column('audit_logs', 'details', new_column_name='description', existing_type=sa.Text(), nullable=True)
    op.alter_column('audit_logs', 'browser', new_column_name='user_agent', existing_type=sa.String(), nullable=False)
    op.alter_column('audit_logs', 'timestamp', new_column_name='created_at', existing_type=sa.DateTime(), nullable=True)
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at', new_column_name='timestamp', existing_type=sa.DateTime(), nullable=True)
    op.alter_column('audit_logs', 'user_agent', new_column_name='browser', existing_type=sa.String(), nullable=False)
    op.alter_column('audit_logs', 'description', new_column_name='details', existing_type=sa.Text(), nullable=True)
    op.alter_column('audit_logs', 'resource_type', new_column_name='entity_name', existing_type=sa.String(), nullable=False)
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'after_values')
    op.drop_column('audit_logs', 'before_values')
    op.drop_column('audit_logs', 'resource_id')
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###
