"""add lead_time_days to products

Revision ID: a9e7a7a62ae1
Revises: 0be900a70bdb
Create Date: 2026-08-27 14:29:52.833972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e7a7a62ae1'
down_revision: Union[str, None] = '0be900a70bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('last_invoice_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_invoice_sequence_company')
    )
    op.create_index(op.f('ix_invoice_sequences_company_id'), 'invoice_sequences', ['company_id'], unique=False)
    op.add_column('products', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.execute(sa.text("UPDATE products SET lead_time_days = 7 WHERE lead_time_days IS NULL"))
    op.alter_column('products', 'lead_time_days', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'lead_time_days')
    op.drop_index(op.f('ix_invoice_sequences_company_id'), table_name='invoice_sequences')
    op.drop_table('invoice_sequences')
    # ### end Alembic commands ###
