"""add import_history and import_errors tables

Revision ID: de2a3aaf1209
Revises: a9e7a7a62ae1
Create Date: 2026-09-06 11:16:50.923441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2a3aaf1209'
down_revision: Union[str, None] = 'a9e7a7a62ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('import_type', sa.Enum('PRODUCTS', 'CUSTOMERS', 'SALES', name='importtype'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('successful_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_history_company_id'), 'import_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_import_history_created_at'), 'import_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_history_import_type'), 'import_history', ['import_type'], unique=False)
    op.create_index(op.f('ix_import_history_status'), 'import_history', ['status'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['import_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_import_id'), 'import_errors', ['import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_errors_import_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_import_history_status'), table_name='import_history')
    op.drop_index(op.f('ix_import_history_import_type'), table_name='import_history')
    op.drop_index(op.f('ix_import_history_created_at'), table_name='import_history')
    op.drop_index(op.f('ix_import_history_company_id'), table_name='import_history')
    op.drop_table('import_history')
    # ### end Alembic commands ###
